# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log_file_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16log_file_service.proto\x12\x10\x63om.example.grpc\"#\n\x0eGetFileRequest\x12\x11\n\tfile_uuid\x18\x01 \x01(\t\"4\n\x11\x43reateFileRequest\x12\x11\n\tfile_uuid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"+\n\x08Response\x12\x11\n\tfile_uuid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t2\xaa\x01\n\x0eLogFileService\x12H\n\x08get_file\x12 .com.example.grpc.GetFileRequest\x1a\x1a.com.example.grpc.Response\x12N\n\x0b\x63reate_file\x12#.com.example.grpc.CreateFileRequest\x1a\x1a.com.example.grpc.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_file_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETFILEREQUEST']._serialized_start=44
  _globals['_GETFILEREQUEST']._serialized_end=79
  _globals['_CREATEFILEREQUEST']._serialized_start=81
  _globals['_CREATEFILEREQUEST']._serialized_end=133
  _globals['_RESPONSE']._serialized_start=135
  _globals['_RESPONSE']._serialized_end=178
  _globals['_LOGFILESERVICE']._serialized_start=181
  _globals['_LOGFILESERVICE']._serialized_end=351
# @@protoc_insertion_point(module_scope)
