"""init

Revision ID: 15e147bb2677
Revises:
Create Date: 2024-03-14 13:23:54.894117

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '15e147bb2677'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
                    sa.Column('uuid', sa.Uuid(), nullable=False),
                    sa.Column('status', sa.Enum('failed', 'in_process',
                              'success', name='statusenum'), nullable=False),
                    sa.PrimaryKeyConstraint('uuid')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
