# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log_file_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16log_file_service.proto\x12\x10\x63om.example.grpc\"#\n\x0eGetFileRequest\x12\x11\n\tfile_uuid\x18\x01 \x01(\t\"\x90\x01\n\x11\x43reateFileRequest\x12\x11\n\tfile_uuid\x18\x01 \x01(\t\x12;\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32-.com.example.grpc.CreateFileRequest.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"~\n\x08Response\x12\x11\n\tfile_uuid\x18\x01 \x01(\t\x12\x32\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32$.com.example.grpc.Response.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xa8\x01\n\x0eLogFileService\x12G\n\x07getFile\x12 .com.example.grpc.GetFileRequest\x1a\x1a.com.example.grpc.Response\x12M\n\ncreateFile\x12#.com.example.grpc.CreateFileRequest\x1a\x1a.com.example.grpc.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_file_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATEFILEREQUEST_DATAENTRY']._options = None
  _globals['_CREATEFILEREQUEST_DATAENTRY']._serialized_options = b'8\001'
  _globals['_RESPONSE_DATAENTRY']._options = None
  _globals['_RESPONSE_DATAENTRY']._serialized_options = b'8\001'
  _globals['_GETFILEREQUEST']._serialized_start=44
  _globals['_GETFILEREQUEST']._serialized_end=79
  _globals['_CREATEFILEREQUEST']._serialized_start=82
  _globals['_CREATEFILEREQUEST']._serialized_end=226
  _globals['_CREATEFILEREQUEST_DATAENTRY']._serialized_start=183
  _globals['_CREATEFILEREQUEST_DATAENTRY']._serialized_end=226
  _globals['_RESPONSE']._serialized_start=228
  _globals['_RESPONSE']._serialized_end=354
  _globals['_RESPONSE_DATAENTRY']._serialized_start=183
  _globals['_RESPONSE_DATAENTRY']._serialized_end=226
  _globals['_LOGFILESERVICE']._serialized_start=357
  _globals['_LOGFILESERVICE']._serialized_end=525
# @@protoc_insertion_point(module_scope)
